version: '3'

services:
  docusaurus:
    image: nginx:alpine
    container_name: docusaurus
    ports:
      - "3000:80"  
    volumes:
      - ./build:/usr/share/nginx/html:ro 
    restart: unless-stopped
