version: '3.8'

services:
  wordpress:
    image: arm64v8/wordpress:latest
    container_name: zai
    restart: always
    ports:
      - "3001:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - caddy

  db:
    image: arm64v8/mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - caddy

networks:
  caddy:
    external: true

volumes:
  wordpress_data:
  db_data:
