version: '3'
services:
  health_check:
    image: nginx:alpine
    container_name: health_check
    ports:
      - "8443:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - caddy

networks:
  caddy:
    external: true