version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - caddy

networks:
  caddy:
    external: true
