name: Docusaurus Build and Deploy

on:
  workflow_run:
    workflows:
      - "Deploy to VPS and start Caddy" 
    types:
      - completed  

jobs:
  docusaurus-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@188.245.182.111 'echo "Connection successful"'
