name: Test SSH Connection

on:
  workflow_dispatch:  # Permite ejecutar el flujo manualmente desde GitHub

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      # Instalar dependencias necesarias en el runner de GitHub Actions
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      # Configurar la llave SSH
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # Probar la conexión SSH con el servidor VPS
      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'Connection successful'"
