name: Test SSH Connection to VPS

on:
  workflow_dispatch: # Permite ejecutar la acción manualmente

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar clave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Verificar conexión SSH
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'Conexión SSH exitosa'"
