name: Test SSH Connection to VPS

on:
  workflow_dispatch: 

jobs:
  ssh-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Connect to VPS and run commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Conexión exitosa al VPS"
            # Aquí puedes agregar otros comandos de prueba para ejecutarlos en el VPS
