name: health-check CI/CD

on:
  workflow_run:
    workflows:
      - "Deploy to VPS and start Caddy"
    types:
      - completed

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Clean up Docker and restart services
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@188.245.182.111 '
            echo "Stopping and removing all Docker containers..." &&
            docker stop $(docker ps -aq) &&
            docker rm $(docker ps -aq) &&
            echo "All containers stopped and removed" &&
            
            echo "Starting Caddy container..." &&
            cd /root/caddy &&
            docker-compose up -d &&
            
            echo "Starting health-check container..." &&
            cd /root/health-check &&
            docker-compose up -d &&
            
            echo "Showing running containers:" &&
            docker ps
          '